hw hb01 is done
vladkuzya/jv-cinema pull request #1
Opened 2020-09-30 11:27 UTC by vladkuzya

2020-09-30 12:06 UTC, aleksandr-hrankin approved these changes

2020-09-30 12:06 UTC, aleksandr-hrankin commented
Good job!

2020-09-30 14:35 UTC, KseniiaMakarova requested changes

2020-09-30 14:35 UTC, KseniiaMakarova commented on pom.xml
> +</project>
let's add the checkstyle plugin

2020-09-30 14:35 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/impl/MovieDaoImpl.java
> +        Session session = HibernateUtil.getSessionFactory().openSession();
move session initialisation inside `try`

2020-09-30 14:35 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/impl/MovieDaoImpl.java
> +            movie.setId(itemId);
please see checklist: you don’t need to set id for your entity explicitly - it will be done by Hibernate :)

2020-09-30 14:35 UTC, KseniiaMakarova commented on src/main/java/mate/academy/dao/impl/MovieDaoImpl.java
> +            session.close();
let's add `if (session != null)` condition here

2020-09-30 14:35 UTC, KseniiaMakarova commented on src/main/resources/hibernate.cfg.xml
> +        <property name="connection.url">jdbc:mysql://localhost/jv-cinema?serverTimezone=UTC</property>
is 3306 used by default?

2020-10-01 07:23 UTC, KseniiaMakarova approved these changes

2020-10-01 07:23 UTC, KseniiaMakarova commented on pom.xml
> +        </plugins>
add the `<pluginManagement>` section as well

2020-10-06 14:47 UTC, merged